[package]
name = "hexagon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17"
parking_lot = "0.12"
rosc = "0.9"
ustr = "0.9"
